---
- name: add sensu core repo
  apt_repository: repo='deb http://repos.sensuapp.org/apt sensu main' state=present
  register: add_sensu_repo

- name: add sensu key
  apt_key: url=http://repos.sensuapp.org/apt/pubkey.gpg state=present
  register: add_sensu_key

- name: install sensu
  when: add_sensu_repo|success and add_sensu_key|success
  apt: pkg=sensu state=installed update_cache=true
  register: install_sensu

# - name: config RMQ-sensu SSL keys
#   script: config_ssl_keys.sh

# - name: config RMQ
#   when: install_rmq|success
#   copy: src=rabbitmq.config dest=/etc/rabbitmq/rabbitmq.config owner=root
#   register: config_rmq
#   notify:
#     - restart RMQ

- name: config sensu RMQ
  template: >
    src=sensu_rmq_config.json.j2
    dest=/etc/sensu/conf.d/rmq.json
    owner={{ sensu_server_user }}
    group={{ sensu_server_group }}
    mode=0640
    backup=yes

- name: config sensu redis
  template: >
    src=sensu_redis_config.json.j2
    dest=/etc/sensu/conf.d/redis.json
    owner={{ sensu_server_user }}
    group={{ sensu_server_group }}
    mode=0640
    backup=yes

- name: config sensu API
  template: >
    src=sensu_api_config.json.j2
    dest=/etc/sensu/conf.d/api.json
    owner={{ sensu_server_user }}
    group={{ sensu_server_group }}
    mode=0640
    backup=yes

- name: add mem check
  copy: >
    src=checks/check_mem.json
    dest=/etc/sensu/conf.d/check_mem.json
    owner={{ sensu_server_user }}
    group={{ sensu_server_group }}

- name: add default handler
  copy: >
    src=handlers/default_handler.json
    dest=/etc/sensu/conf.d/default_handler.json
    owner={{ sensu_server_user }}
    group={{ sensu_server_group }}

- name: set sensu config folder permissions
  file: >
    path=/etc/sensu
    owner={{ sensu_server_user }}
    group={{ sensu_server_group }}
    recurse=yes
  notify:
    - restart sensu server
