---
- name: add sensu core repo
  apt_repository: repo='deb http://repos.sensuapp.org/apt sensu main' state=present
  register: add_sensu_repo

- name: add sensu key
  apt_key: url=http://repos.sensuapp.org/apt/pubkey.gpg state=present
  register: add_sensu_key

- name: install sensu
  when: add_sensu_repo|success and add_sensu_key|success
  apt: pkg=sensu state=installed update_cache=true
  register: install_sensu
  notify:
    - enable RMQ

- name: config RMQ-sensu SSL keys
  script: config_ssl_keys.sh

- name: add RMQ sensu vhost
  rabbitmq_vhost: name={{ rmq_sensu_vhost }}
  register: config_sensu_vhost

- name: add RMQ sensu user
  when: config_sensu_vhost|success
  rabbitmq_user: name={{ rmq_sensu_user_name }}
                 password={{ rmq_sensu_user_pass }}
                 vhost={{ rmq_sensu_vhost }}
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present

- name: config RMQ
  when: install_rmq|success
  copy: src=rabbitmq.config dest=/etc/rabbitmq/rabbitmq.config owner=root
  register: config_rmq
  notify:
    - restart RMQ

- name: config sensu connections
  when: config_rmq|success
  template:
    src=sensu.config.json.j2
    dest=/etc/sensu/config.json
    owner=sensu
    group=sensu
    mode=0640
    backup=yes
  register: config_sensu_connections

- name: add mem check
  when: config_sensu_connections|success
  copy: src=checks/check_mem.json
        dest=/etc/sensu/conf.d/check_mem.json
        owner=sensu
        group=sensu

- name: add default handler
  when: config_sensu_connections|success
  copy: src=handlers/default_handler.json
        dest=/etc/sensu/conf.d/default_handler.json
        owner=sensu
        group=sensu
  notify:
    - start sensu server
    - start sensu api
