---
- name: restart RMQ
  service: name=rabbitmq-server state=restarted

- name: restart sensu server
  service: name=sensu-{{ api }} state=restarted
  with_items:
    - server
    - api
  when: install_sensu_server
